version: "3.8"
services:
  oAuth:
    image: myapp:latest
    ports:
      - 4000:4010
    deploy:
      replicas: 5


#   web:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ./html:/usr/share/nginx/html:ro
#     restart: unless-stopped

#   app:
#     image: myapp:latest
#     build:
#       context: ./app
#       dockerfile: Dockerfile
#     environment:
#       - APP_ENV=production
#       - APP_DEBUG=false
#     depends_on:
#       - db
#     ports:
#       - "8080:8080"
#     restart: unless-stopped

#   db:
#     image: postgres:13
#     environment:
#       - POSTGRES_USER=myuser
#       - POSTGRES_PASSWORD=mypassword
#       - POSTGRES_DB=mydatabase
#     volumes:
#       - db_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     restart: unless-stopped

# volumes:
#   db_data: